[project]
name = "odoo-addons-oca-bank-payment"
version = "18.0.20250422.0"
dependencies = [
    "odoo-addon-account_banking_mandate==18.0.*",
    "odoo-addon-account_banking_mandate_contact==18.0.*",
    "odoo-addon-account_invoice_select_for_payment==18.0.*",
    "odoo-addon-account_payment_mode==18.0.*",
    "odoo-addon-account_payment_order==18.0.*",
    "odoo-addon-account_payment_partner==18.0.*",
    "odoo-addon-account_payment_purchase==18.0.*",
    "odoo-addon-account_payment_sale==18.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 18.0",
]
